name: BlueMap
main: de.bluecolored.bluemap.bukkit.BukkitPlugin
version: 0.2.1
author: Blue (TBlueF / Lukas Rieger)
authors: [Blue (TBlueF / Lukas Rieger)]
website: "https://github.com/BlueMap-Minecraft"
commands: 
  bluemap: