name: BlueMap
description: "A 3d-map of your Minecraft worlds view-able in your browser using three.js (WebGL)"
main: de.bluecolored.bluemap.bukkit.BukkitPlugin
version: 0.3.0
author: "Blue (TBlueF / Lukas Rieger)"
authors: [Blue (TBlueF / Lukas Rieger)]
website: "https://github.com/BlueMap-Minecraft"
commands: 
  bluemap:
    description: Root command for all bluemap commands
    permission: bluemap
    usage: |
           /<command>
           /<command> reload
           /<command> pause
           /<command> resume
           /<command> render [world]
           /<command> debug
permissions:
  bluemap.*:
    children:
      bluemap.status: true
      bluemap.reload: true
      bluemap.pause: true
      bluemap.resume: true
      bluemap.rendertask.create.world: true
      bluemap.rendertask.prioritize: true
      bluemap.rendertask.remove: true
      bluemap.debug: true
    default: op
  bluemap.status:
    default: op
  bluemap.reload:
    default: op
  bluemap.pause:
    default: op
  bluemap.resume:
    default: op
  bluemap.rendertask.create.world:
    default: op
  bluemap.rendertask.prioritize:
    default: op
  bluemap.rendertask.remove:
    default: op
  bluemap.debug:
    default: op