name: BlueMap
main: de.bluecolored.bluemap.bukkit.BukkitPlugin
version: 0.1.0
author: Blue (TBlueF / Lukas Rieger)
authors: [Blue (TBlueF / Lukas Rieger)]
website: "https://github.com/BlueMap-Minecraft"
commands: 
