name: BlueMap
description: "A 3d-map of your Minecraft worlds view-able in your browser using three.js (WebGL)"
main: de.bluecolored.bluemap.bukkit.BukkitPlugin
version: ${version}
api-version: 1.16
author: "Blue (TBlueF / Lukas Rieger)"
website: "https://github.com/BlueMap-Minecraft"
commands:
permissions:
  bluemap.*:
    children:
      bluemap.status: true
      bluemap.reload: true
      bluemap.pause: true
      bluemap.resume: true
      bluemap.render: true
      bluemap.debug: true
      bluemap.marker: true
    default: op
  bluemap.status:
    default: op
  bluemap.reload:
    default: op
  bluemap.pause:
    default: op
  bluemap.resume:
    default: op
  bluemap.render:
    default: op
  bluemap.debug:
    default: op
  bluemap.marker:
    default: op